Update pre-commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,10 +1,13 @@
-#!/bin/sh
+#!/usr/bin/env bash
 #
 # An example hook script to verify what is about to be committed.
 # Called by "git commit" with no arguments.  The hook should
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
-#
+
+# Propagate failures:
+set -euo pipefail
+
 # To enable this hook, rename this file to "pre-commit".
 
 # Build dist/index.js:
